name: run checks
on:
  pull_request:
    branches:
      - main
    paths:
      - '**.py'

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        # change this python version if the python version is changed in pyproject.toml and the Dockerfile
        python-version: '{{cookiecutter.python_version}}'
    - name: Set up Poetry
      uses: abatilo/actions-poetry@v4
      with:
        poetry-version: 1.7.1
    - name: Install dependencies
      run: poetry config virtualenvs.create true --local && poetry config virtualenvs.in-project true --local && poetry install --no-interaction
    - name: run mypy
      run: poetry run mypy
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        # change this python version if the python version is changed in pyproject.toml and the Dockerfile
        python-version: '{{cookiecutter.python_version}}'
    - name: Set up Poetry
      uses: abatilo/actions-poetry@v4
      with:
        poetry-version: 1.7.1
    - name: Install dependencies
      run: poetry config virtualenvs.create true --local && poetry config virtualenvs.in-project true --local && poetry install --no-interaction
    - name: run tests
      run: poetry run pytest tests
